### ISSUE TITLE
Is it possible to hide the process?

### ISSUE THREAD

**Issue by yaoh3i** [Gui774ume/ebpfkit#3]
Surprising ideas! I have a question. General rootkits can hide specific processes and prevent them from being detected by commands such as ps. Is this possible for ebpfkit?

**Comment by Gui774ume** [comment]
Hey there,

Yes, if you have a look [here](https://github.com/Gui774ume/ebpfkit/blob/387dba934ac9ad6d5b4a57315e3d6acb9cfecfc2/pkg/ebpfkit/ebpfkit.go#L459), you'll see that we hide the pid from the `proc` file system. If you wanted to hide a file, or the process binary itself, you could simply do what we do to hide the binary of the rootkit [here](https://github.com/Gui774ume/ebpfkit/blob/387dba934ac9ad6d5b4a57315e3d6acb9cfecfc2/pkg/ebpfkit/ebpfkit.go#L462).

We haven't made this feature configurable but we didn't need to do it for our research (we just wanted to show that it was possible).

I hope this helps !
